### ISSUE TITLE
Unhandled error with GPT-4 model

### ISSUE THREAD

**Issue by EuleMitKeule** [FujiwaraChoki/NotesTaker#6]
When GPT-4 is selected as model an unhandled backend error occurs due to a malformed request body which leads to an invalid summary. This error should be fixed and similar errors should be handled gracefully.

**Comment by FujiwaraChoki** [comment]
Include more information, screenshots, commands you ran, etc.

**Comment by EuleMitKeule** [comment]
```py
response = g4f.ChatCompletion.create(
        model=mdl, messages=[{"role": "user", "content": prompt}]
)
```

Returns `<PHIND_BACKEND_ERROR>Invalid request body</PHIND_BACKEND_ERROR>`
When model is kept at the default value of `gpt-4`.

**Comment by FujiwaraChoki** [comment]
https://github.com/xtekky/gpt4free/issues/1542

**Comment by hlohaus** [comment]
I created a update for the Phind provider. I generate now a challenge value for each request.
